### PR TITLE
Added TimeSaver Website

### PR DESCRIPTION
**Pull request by willdenms**
Added TimeSaver Website directory with all of its supporting files and documents

### CODE REVIEW

**Comment by jwiese** [comment]
Should be in the _projects/timesaver folder (follow the lowercase naming convention)

**Comment by willdenms** [comment]
My apologies, I was admittedly a little confused on how you wanted it. Would you like me to resubmit?

**Comment by jwiese** [comment]
No problem, please do resubmit.

**Comment by willdenms** [comment]
changed directory

**Pull request merged**
